// Copyright 2015 Satoshi Konno. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package method

const (
	SystemMethodPostJob             = "post_job"
	SystemMethodPostMethod          = "post_method"
	SystemMethodSetMethod           = "set_method"
	SystemMethodSetAlias            = "set_alias"
	SystemMethodSetRoute            = "set_route"
	SystemMethodSetTimer            = "set_timer"
	SystemMethodAddNode             = "add_node"
	SystemMethodRemoveMethod        = "remove_method"
	SystemMethodRemoveAlias         = "remove_alias"
	SystemMethodRemoveRoute         = "remove_route"
	SystemMethodRemoveTimer         = "remove_timer"
	SystemMethodRemoveNode          = "remove_node"
	SystemMethodEcho                = "_echo"
	SystemMethodGetNetworkState     = "get_network_state"
	SystemMethodGetClusterState     = "get_cluster_state"
	SystemMethodSetRegistry         = "set_registry"
	SystemMethodGetRegistry         = "get_registry"
	SystemMethodRemoveRegistry      = "remove_registry"
	SystemMethodGetNodeState        = "get_node_state"
	SystemMethodGetNodeConfig       = "get_node_config"
	SystemMethodParamId             = "id"
	SystemMethodParamName           = "name"
	SystemMethodParamLanguage       = "lang"
	SystemMethodParamCode           = "code"
	SystemMethodParamEncode         = "enc"
	SystemMethodParamBase64         = "base64"
	SystemMethodParamKey            = "key"
	SystemMethodParamValue          = "val"
	SystemMethodParamTs             = "ts"
	SystemMethodParamLts            = "lts"
	SystemMethodParamSrc            = "src"
	SystemMethodParamDest           = "dest"
	SystemMethodParamType           = "type"
	SystemMethodParamCond           = "cond"
	SystemMethodParamAddr           = "addr"
	SystemMethodParamPort           = "port"
	SystemMethodParamHash           = "hash"
	SystemMethodParamVersion        = "version"
	SystemMethodParamNodes          = "nodes"
	SystemMethodParamCluster        = "cluster"
	SystemMethodParamClusters       = "clusters"
	SystemMethodParamState          = "state"
	SystemMethodParamMethod         = "method"
	SystemMethodParamDefaults       = "defaults"
	SystemMethodParamStartTime      = "start_time"
	SystemMethodParamStopTime       = "stop_time"
	SystemMethodParamDuration       = "duration"
	SystemMethodParamLoop           = "loop"
	SystemMethodAddNodeCmd          = "/usr/local/bin/roundd"
	SystemMethodRemoveNodeDelayMsec = 5000
	SystemMethodDestAllNode         = "*"
	SystemMethodDestAnyNode         = "?"
	SystemMethodDestLocalNode       = "."
	SystemMethodRouteTypePipe       = "pipe"
	SystemMethodRouteTypeEvent      = "event"
)
